services:
  python-fastapi:
    image: python-fastapi
    container_name: python-fastapi
    env_file:
      - .env.example
    ports:
      - "8000:8000"
    environment:
      - TZ=Asia/Jakarta
    networks:
      - python-fastapi
      - db-server
    restart: unless-stopped
networks:
  python-fastapi:
    external: true
  db-server:
    external: true